[package]
name = "tic-tac-toe"
version = "0.1.0"
authors = ["trolleyman <cgtrolley@gmail.com>"]

[dependencies]
gtk = { git = "https://github.com/gtk-rs/gtk.git" }
byteorder = { git = "https://github.com/trolleyman/byteorder.git" }
